import { useEffect, useState } from 'react';
import API from '../api/axios';

export default function FpoCompletionPanel({ profile, farmers, batches, onRefresh }) {
  const [prices,setPrices]=useState([]); const [weekly,setWeekly]=useState([]); const [staff,setStaff]=useState([]);
  const [price,setPrice]=useState({cropName:'',gradeAPricePerKg:'',gradeBPricePerKg:'',gradeCPricePerKg:'',referenceMarketPrice:''});
  const [profileForm,setProfileForm]=useState({name:'',registrationNumber:'',cbboName:'',managerName:'',managerContact:'',phone:'',email:'',address:'',district:'',state:'',pincode:'',creditLineAvailable:0});
  const [excel,setExcel]=useState(null); const [staffForm,setStaffForm]=useState({name:'',email:'',password:'',location:''});
  const [payoutBatch,setPayoutBatch]=useState(''); const [preview,setPreview]=useState(null); const [message,setMessage]=useState('');

  useEffect(()=>{if(!profile)return;setProfileForm({name:profile.name||'',registrationNumber:profile.registrationNumber||'',cbboName:profile.cbboName||'',managerName:profile.managerName||'',managerContact:profile.managerContact||'',phone:profile.contactDetails?.phone||'',email:profile.contactDetails?.email||'',address:profile.contactDetails?.address||'',district:profile.contactDetails?.district||'',state:profile.contactDetails?.state||'',pincode:profile.contactDetails?.pincode||'',creditLineAvailable:profile.creditLineAvailable||0});load();},[profile]);
  const load=async()=>{try{const [p,w,s]=await Promise.all([API.get('/grade-prices'),API.get('/reports/weekly'),API.get('/fpo/profile').then(r=>r.data.staff||[])]);setPrices(p.data);setWeekly(w.data);setStaff(s);}catch(e){console.error(e)}};
  const saveProfile=async e=>{e.preventDefault();try{const r=await API.patch('/fpo/profile',{name:profileForm.name,registrationNumber:profileForm.registrationNumber,cbboName:profileForm.cbboName,managerName:profileForm.managerName,managerContact:profileForm.managerContact,creditLineAvailable:Number(profileForm.creditLineAvailable),contactDetails:{phone:profileForm.phone,email:profileForm.email,address:profileForm.address,district:profileForm.district,state:profileForm.state,pincode:profileForm.pincode}});setMessage('FPO profile updated.');onRefresh?.(r.data); }catch(e){setMessage(e.response?.data?.message||'Profile update failed.')}};
  const savePrice=async e=>{e.preventDefault();try{await API.post('/grade-prices',{...price,gradeAPricePerKg:Number(price.gradeAPricePerKg),gradeBPricePerKg:Number(price.gradeBPricePerKg),gradeCPricePerKg:Number(price.gradeCPricePerKg),referenceMarketPrice:Number(price.referenceMarketPrice)||0});setPrice({cropName:'',gradeAPricePerKg:'',gradeBPricePerKg:'',gradeCPricePerKg:'',referenceMarketPrice:''});setMessage('Grade pricing saved.');load();}catch(e){setMessage(e.response?.data?.message||'Could not save pricing.')}};
  const importExcel=async e=>{e.preventDefault();if(!excel)return;try{const f=new FormData();f.append('file',excel);const r=await API.post('/fpo/farmers/import-excel',f,{headers:{'Content-Type':'multipart/form-data'}});setMessage(r.data.message);setExcel(null);onRefresh?.();}catch(e){setMessage(e.response?.data?.message||'Excel import failed.')}};
  const addStaff=async e=>{e.preventDefault();try{await API.post('/fpo/staff',staffForm);setStaffForm({name:'',email:'',password:'',location:''});setMessage('Staff member added.');load();}catch(e){setMessage(e.response?.data?.message||'Staff creation failed.')}};
  const removeStaff=async id=>{if(!confirm('Deactivate this staff member?'))return;try{await API.delete(`/fpo/staff/${id}`);setMessage('Staff member deactivated.');load();}catch(e){setMessage(e.response?.data?.message||'Could not remove staff.')}};
  const payoutPreview=async()=>{try{const r=await API.get(`/fpo/batches/${payoutBatch}/payout-preview`);setPreview(r.data);}catch(e){setPreview(null);setMessage(e.response?.data?.message||'Payout preview failed.')}};
  const pay=async()=>{try{await API.post(`/fpo/batches/${payoutBatch}/payout`,{paymentMethod:'BANK_TRANSFER',fundedFrom:'FPO_CASH',transactionId:prompt('Enter transaction ID (leave blank for Pending):')||undefined});setMessage('Payout recorded.');setPreview(null);onRefresh?.();}catch(e){setMessage(e.response?.data?.message||'Payout failed.')}};
  return <div className="space-y-6">
    {message&&<div className="bg-emerald-50 border border-emerald-200 text-emerald-800 p-3 rounded-lg text-sm">{message}</div>}
    <section className="bg-white p-6 rounded-xl shadow-sm border border-gray-100"><h2 className="text-2xl font-bold text-gray-800 mb-4">FPO Completion Center</h2><p className="text-sm text-gray-500">All remaining FPO operations: profile, disclosed grade pricing, automatic farmer payout, Excel import, staff control and weekly reporting.</p></section>
    <form onSubmit={saveProfile} className="bg-white p-6 rounded-xl shadow-sm border grid md:grid-cols-2 gap-3"><h3 className="md:col-span-2 font-semibold">Edit FPO Profile & Contact</h3>{['name','registrationNumber','cbboName','managerName','managerContact','phone','email','address','district','state','pincode','creditLineAvailable'].map(k=><input key={k} type={k==='creditLineAvailable'?'number':k==='email'?'email':'text'} value={profileForm[k]} onChange={e=>setProfileForm({...profileForm,[k]:e.target.value})} placeholder={k} className="p-2.5 border rounded-lg" />)}<button className="md:col-span-2 bg-emerald-600 text-white py-2.5 rounded-lg">Save Profile</button></form>
    <div className="grid lg:grid-cols-2 gap-6"><form onSubmit={savePrice} className="bg-white p-6 rounded-xl shadow-sm border space-y-3"><h3 className="font-semibold">Grade Price Configuration</h3><input placeholder="Crop name" value={price.cropName} onChange={e=>setPrice({...price,cropName:e.target.value})} className="w-full p-2.5 border rounded-lg" required/><div className="grid grid-cols-3 gap-2">{['A','B','C'].map(g=><input key={g} type="number" min="0" step="0.01" placeholder={`Grade ${g} ₹/kg`} value={price[`grade${g}PricePerKg`]} onChange={e=>setPrice({...price,[`grade${g}PricePerKg`]:e.target.value})} className="p-2.5 border rounded-lg" required/>)}</div><input type="number" min="0" step="0.01" placeholder="Reference market price ₹/kg" value={price.referenceMarketPrice} onChange={e=>setPrice({...price,referenceMarketPrice:e.target.value})} className="w-full p-2.5 border rounded-lg"/><button className="w-full bg-emerald-600 text-white py-2.5 rounded-lg">Save New Pricing</button><div className="text-xs text-gray-500">Existing configurations are retained as history; the newest active configuration is used for grading.</div></form>
      <div className="bg-white p-6 rounded-xl shadow-sm border"><h3 className="font-semibold mb-3">Active / Historical Prices</h3>{prices.map(p=><div key={p._id} className="border-b py-2 text-sm flex justify-between"><span>{p.cropName} — A ₹{p.gradeAPricePerKg} / B ₹{p.gradeBPricePerKg} / C ₹{p.gradeCPricePerKg}</span><span>{p.isActive?'Active':'Historical'}</span></div>)}{!prices.length&&<p className="text-sm text-gray-400">No price configurations yet.</p>}</div></div>
    <div className="grid lg:grid-cols-2 gap-6"><form onSubmit={importExcel} className="bg-white p-6 rounded-xl shadow-sm border space-y-3"><h3 className="font-semibold">Excel Farmer Import</h3><p className="text-xs text-gray-500">Columns: name, phone, aadhaarNumber, address, accountNumber, ifscCode, bankName.</p><input type="file" accept=".xlsx,.xls" onChange={e=>setExcel(e.target.files?.[0]||null)} required/><button className="bg-emerald-600 text-white px-4 py-2 rounded-lg">Import Excel</button></form>
      <div className="bg-white p-6 rounded-xl shadow-sm border"><h3 className="font-semibold mb-3">Automatic Grade-Based Payout</h3><select value={payoutBatch} onChange={e=>{setPayoutBatch(e.target.value);setPreview(null)}} className="w-full p-2.5 border rounded-lg"><option value="">Select approved batch</option>{batches.filter(b=>b.grading?.status==='Approved'&&b.payoutStatus!=='PAID').map(b=><option key={b._id} value={b._id}>{b.batchId} — {b.produceType} — ₹{b.amountOwedToFarmer||0}</option>)}</select><button type="button" onClick={payoutPreview} disabled={!payoutBatch} className="mt-2 bg-gray-800 text-white px-4 py-2 rounded-lg disabled:opacity-40">Calculate Preview</button>{preview&&<div className="mt-3 bg-gray-50 p-3 rounded-lg text-sm">A: {preview.breakdown.A.kg}kg × ₹{preview.breakdown.A.pricePerKg}<br/>B: {preview.breakdown.B.kg}kg × ₹{preview.breakdown.B.pricePerKg}<br/>C: {preview.breakdown.C.kg}kg × ₹{preview.breakdown.C.pricePerKg}<div className="font-bold mt-2">Total owed: ₹{preview.totalAmount}</div><button onClick={pay} className="mt-2 bg-emerald-600 text-white px-4 py-2 rounded-lg">Record Payout</button></div>}</div></div>
    <div className="grid lg:grid-cols-2 gap-6"><div className="bg-white p-6 rounded-xl shadow-sm border"><h3 className="font-semibold mb-3">Staff Management</h3><form onSubmit={addStaff} className="grid grid-cols-2 gap-2 mb-4">{['name','email','password','location'].map(k=><input key={k} type={k==='email'?'email':k==='password'?'password':'text'} placeholder={k} value={staffForm[k]} onChange={e=>setStaffForm({...staffForm,[k]:e.target.value})} className="p-2 border rounded-lg" required/>)}<button className="col-span-2 bg-emerald-600 text-white py-2 rounded-lg">Add Staff</button></form>{staff.map(s=><div key={s._id} className="flex justify-between items-center border-b py-2 text-sm"><span>{s.name} — {s.email}</span><button onClick={()=>removeStaff(s._id)} className="text-red-600">Deactivate</button></div>)}</div>
      <div className="bg-white p-6 rounded-xl shadow-sm border"><h3 className="font-semibold mb-3">Weekly Report</h3>{weekly.map(w=><div key={w.week} className="flex justify-between border-b py-2 text-sm"><span>Week of {w.week}</span><span>{w.intakeKg}kg · ₹{w.revenue}</span></div>)}{!weekly.length&&<p className="text-sm text-gray-400">No weekly data yet.</p>}</div></div>
  </div>;
}
